services:
  - type: web
    name: booking-page-idi
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: AZURE_REFRESH_TOKEN
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
